kind: Pod
apiVersion: v1
metadata:
  name: jnlp
  namespace: jenkins
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk11
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 300m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  - name: go
    image: golang:1.17
    imagePullPolicy: IfNotPresent
    env:
      - name: GOPROXY
        value: https://goproxy.cn
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 500m
        memory: 2000Mi
      requests:
        cpu: 300m
        memory: 1000Mi
  - name: docker
    image: docker:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: DOCKER_BUILDKIT
        value: 0
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 300m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 500Mi
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
