kind: Pod
apiVersion: v1
metadata:
  name: jnlp
  namespace: jenkins
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk11
    imagePullPolicy: Always
  - name: maven
    image: maven:3.8.6-jdk-8-slim
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /usr/local/maven/repository
      name: jenkins-maven
    command:
    - cat
    tty: true
  - name: docker
    image: docker:latest
    imagePullPolicy: Always
    env:
      - name: DOCKER_BUILDKIT
        value: 0
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
    command:
    - cat
    tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: jenkins-maven
      persistentVolumeClaim:
        claimName: jenkins-maven
