kind: Pod
apiVersion: v1
metadata:
  name: jnlp
  namespace: jenkins
spec:
  # securityContext:
  #   runAsUser: 0
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:jdk21
    imagePullPolicy: IfNotPresent
    env:
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: K8S_NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
  - name: go
    image: golang:1.24
    imagePullPolicy: IfNotPresent
    env:
      - name: GOPROXY
        value: https://goproxy.cn
      - name: GOPATH
        value: /go
    command:
    - cat
    volumeMounts:
      - mountPath: /go
        name: go-cache
    tty: true
  - name: buildah
    # image: quay.io/buildah/stable:latest
    image: quay.nju.edu.cn/buildah/stable:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: LANG
        value: "C.UTF-8"
    command:
      - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - name: registries-conf
        mountPath: /etc/containers/registries.conf
        subPath: registries.conf
  volumes:
    - name: registries-conf
      configMap:
        name: buildah-registries-conf
    - name: go-cache
      persistentVolumeClaim:
        claimName: jenkins-go-cache
