kind: Pod
apiVersion: v1
metadata:
  name: jnlp
  namespace: jenkins
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk17
    imagePullPolicy: IfNotPresent
  - name: maven
    image: maven:3.8.6-jdk-8-slim
    imagePullPolicy: IfNotPresent
    command:
    - cat
    resources:
      limits:
        cpu: 2500m
        memory: 4000Mi
      requests:
        cpu: 1000m
        memory: 2000Mi
    volumeMounts:
    - mountPath: /usr/local/maven/repository
      name: jenkins-maven
    tty: true
  - name: docker
    image: docker:latest
    imagePullPolicy: IfNotPresent
    command:
    - cat
    env:
      - name: DOCKER_BUILDKIT
        value: 0
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: dockersock
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: IfNotPresent
    command:
    - cat
    env:
      - name: KANIKO_REGISTRY_MAP
        value: index.docker.io=dockerproxy.com;index.docker.io=docker.mirrors.ustc.edu.cn;index.docker.io=docker.nju.edu.cn
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: jenkins-maven
      persistentVolumeClaim:
        claimName: jenkins-maven
    - name: kaniko-secret
      secret:
        secretName: registry-secret
        items:
          - key: .dockerconfigjson
            path: config.json
